name: immuneml_tools
owner: pavelva
description: "immuneML is a platform for machine learning-based analysis and classification of adaptive immune receptors and repertoires (AIRR)."
categories:
  - "Machine Learning"